# .github/workflows/build.yml
name: Build and Package

on: [push, pull_request]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, aarch64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-12 \
          build-essential \
          cmake \
          libpaho-mqtt-dev \
          libpaho-mqttpp-dev \
          libboost-all-dev \
          libjsoncpp-dev \
          dpkg-dev \
          ubuntu-dev-tools

    # - name: Cache CMake
    #   uses: actions/cache@v2
    #   with:
    #     path: /root/.cache/cmake
    #     key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        export CC=gcc-12
        export CXX=g++-12
        cmake  ..
        cmake --build . --config Release

    - name: Package DEB
      run: |
        cd build
        cpack -G DEB

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: homed-exporter-${{ matrix.arch }}
        path: build/*.deb
